### =======================================
### 1. RECURSO: /usuarios
### =======================================

### 1.1 CREAR USUARIO (POST)
# Ejecuta esta para que exista el usuario con ID 1
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nombre": "Mariano",
  "correo": "mariano@example.com"
}

### 1.2 CREAR SEGUNDO USUARIO (POST)
# Ejecuta esta para probar la lista, el ID será 2
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nombre": "Ramiro",
  "correo": "ramiro@example.com"
}

### 1.3 LISTAR TODOS LOS USUARIOS (GET /)
GET http://localhost:3000/usuarios

### 1.4 OBTENER USUARIO POR ID (GET /:id)
# Debería devolver el usuario con ID 1 (Mariano)
GET http://localhost:3000/usuarios/1

### 1.5 ACTUALIZAR USUARIO (PUT /:id)
# Actualiza el nombre y el estado del usuario con ID 1
PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
  "nombre": "Mariano. Q",
  "estado": "Activo"
}

### 1.6 OBTENER USUARIO POR ID después de actualizar (GET /:id)
# Verifica los cambios en el usuario 1
GET http://localhost:3000/usuarios/1

### 1.7 ELIMINAR USUARIO (DELETE /:id)
# Elimina el usuario con ID 2 (Mariano)
DELETE http://localhost:3000/usuarios/2

### 1.8 LISTAR USUARIOS para verificar la eliminación (GET /)
# Ahora solo debería aparecer el usuario con ID 1
GET http://localhost:3000/usuarios

### Crear equipo (usa el id del usuario creado arriba)
POST http://localhost:3000/equipos
Content-Type: application/json

{
  "nombre": "Equipo IT",
  "creado_por": 1
}

###

### Listar equipos
GET http://localhost:3000/equipos

###

### Crear tarea
POST http://localhost:3000/tareas
Content-Type: application/json

{
  "titulo": "Hacer el informe",
  "descripcion": "Terminar el trabajo práctico",
  "creador_id": 1,
  "equipo_id": 1,
  "fecha_vencimiento": "2025-09-30"
}

###

### Listar tareas
GET http://localhost:3000/tareas

###

### Editar tarea (id = 1)
PUT http://localhost:3000/tareas/1
Content-Type: application/json

{
  "titulo": "Hacer el informe actualizado",
  "descripcion": "TP versión final",
  "prioridad": 2
}

###

### Cambiar estado de la tarea (PENDIENTE -> EN_PROGRESO)
PATCH http://localhost:3000/tareas/1/estado
Content-Type: application/json

{
  "nuevoEstado": "EN_PROGRESO"
}

###


### Borrar tarea (id = 1)
DELETE http://localhost:3000/tareas/1

###


